version: '3.4'
services:
  sio.google.synthesiser:
    environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=https://+:443;http://+:80
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
          - ASPNETCORE_Kestrel__Certificates__Default__Password=1qaz-pl,
          - FUNCTIONS_WORKER_RUNTIME=dotnet
          - AzureWebJobsScriptRoot=/home/site/wwwroot
          - AzureFunctionsJobHost__Logging__Console__IsEnabled=true
          - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://host.docker.internal:10000/devstoreaccount1;QueueEndpoint=http://host.docker.internal:10001/devstoreaccount1;
    ports:
          - "80"
          - "443"
    volumes:
          - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
          - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
          - ${USERPROFILE}\.aspnet\https:/https/
