version: '3.4'

services:
  sio.google.synthesiser:
    image: ${DOCKER_REGISTRY-}synthesiser
    container_name: sio.google.synthesiser
    build:
      context: .
      dockerfile: src/SIO.Google.Synthesiser/Dockerfile
networks:    
  default:
    external:
        name: sio.network